fix: static analysis issues
dirablue/plist_parser pull request #19
Opened 2023-11-12 20:34 UTC by DrzwiPercepcji

1. Fixed pub.dev static analysis issues:
![obraz](https://github.com/dirablue/plist_parser/assets/32015883/2a712d38-3e47-4244-bfd0-837b7d0dbc5d)

2023-11-15 12:08 UTC, dirablue requested changes
@DrzwiPercepcji 
Hi, Thank you for updating your code!
It's great.

it seems format check is failed, I think only one point I commented. could you check?

2023-11-15 12:08 UTC, dirablue commented on lib/plist_parser.dart
> +        children.where((el) => el.name.local == 'key').map((el) => el.innerText);
```suggestion
    final keys = children
        .where((el) => el.name.local == 'key')
        .map((el) => el.innerText);
```

fixed format with dart formatter

2023-11-15 12:38 UTC, DrzwiPercepcji commented on lib/plist_parser.dart
> +        children.where((el) => el.name.local == 'key').map((el) => el.innerText);
@dirablue fixed.

2023-11-16 01:35 UTC, merged

2023-11-16 01:47 UTC, dirablue commented
@DrzwiPercepcji 
thanks! 
I published new version v0.0.11 to pub.dev
https://pub.dev/packages/plist_parser